--- 
- name: nginx installation 
  hosts: web 
  become: yes 
  tasks: 
  - name: Install nginx web service 
    ansible.builtin.package: 
      name: nginx 
      state: present 
  - name: Start the Nginx service 
    ansible.builtin.service: 
      name: nginx 
      state: started 
      enabled: yes 