--- 
- name: shell vs command modules 
  hosts: local 
  connection: local 
  tasks: 
  - name: execute the command 
    ansible.builtin.shell: ls -ltr > /tmp/output.txt 
  
  - name: execute the ls command in command module without redirecters 
    ansible.builtin.command: ls -ltr 