--- 
- name: Create EC2 instances and Route53 records 
  hosts: local 
  connection: local 
  vars: 
    subnet_id: subnet-017b8c44879e7db1b
    sg_id: sg-0a3b9d8fc83074f17
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro 
    zone: tridev.online
    instances: 
    - mysql 
    - backend 
    - frontend 
  tasks: 
  - name: install aws python libraries 
    ansible.builtin.pip: 
      name: "{{ item }}"
      executable: pip3.9 
    loop: 
    - botocore 
    - boto3

  - name: create ec2 instance 
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_info 
  
  # - name: print ec2 info 
  #   ansible.builtin.debug: 
  #     msg: "{{ ec2_info }}"
    
  # - name: print ec2 private ips
  #   ansible.builtin.debug:
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_info.results }}"
  
  # - name: print instance name and private ip
  #   ansible.builtin.debug:
  #     msg: "{{ item.item }} => {{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_info.results }}"

  - name: Print only private IPs
    ansible.builtin.debug:
      msg: "{{ ec2_info.results | map(attribute='instances') | map('first') | map(attribute='private_ip_address') | list }}"
  

  - name: Build instance name to private IP map
    ansible.builtin.set_fact:
      instance_ip_map: >-
        {{
          instance_ip_map | default({}) |
          combine({ item.item: item.instances[0].private_ip_address })
        }}
    loop: "{{ ec2_info.results }}"

  - name: Show instance → private IP mapping
    ansible.builtin.debug:
      var: instance_ip_map

  - name: Create route53 records
  amazon.aws.route53:
    state: present
    zone: "{{ zone }}"
    record: "{{ item.item }}.{{ zone }}"
    type: A
    ttl: 1
    value: "{{ item.instances[0].private_ip_address }}"
    wait: true
    overwrite: true 
  loop: "{{ ec2_info.results }}"
